config/routes.rb
Rails.application.routes.draw do
  resources :check_ins
  resources :roasts
  devise_for :users

  root "check_ins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/check_in.rb
class CheckIn < ApplicationRecord
  belongs_to :user
  belongs_to :roast
end

app/models/roast.rb
class Roast < ApplicationRecord
  has_many :check_ins
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :check_ins
  has_many :roasts, through: :check_ins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/check_ins_controller.rb
class CheckInsController < ApplicationController
  before_action :set_check_in, only: [:show, :edit, :update, :destroy]

  # GET /check_ins
  # GET /check_ins.json
  def index
    @check_ins = current_user.check_ins.all
  end

  # GET /check_ins/1
  # GET /check_ins/1.json
  def show
  end

  # GET /check_ins/new
  def new
    @check_in = current_user.check_ins.new
  end

  # GET /check_ins/1/edit
  def edit
  end

  # POST /check_ins
  # POST /check_ins.json
  def create
    @check_in = current_user.check_ins.new(check_in_params)

    respond_to do |format|
      if @check_in.save
        format.html { redirect_to @check_in, notice: 'Check in was successfully created.' }
        format.json { render :show, status: :created, location: @check_in }
      else
        format.html { render :new }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /check_ins/1
  # PATCH/PUT /check_ins/1.json
  def update
    respond_to do |format|
      if @check_in.update(check_in_params)
        format.html { redirect_to @check_in, notice: 'Check in was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_in }
      else
        format.html { render :edit }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_ins/1
  # DELETE /check_ins/1.json
  def destroy
    @check_in.destroy
    respond_to do |format|
      format.html { redirect_to check_ins_url, notice: 'Check in was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_in
      @check_in = current_user.check_ins.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_in_params
      params.require(:check_in).permit(:roast_id, :location)
    end
end

app/controllers/roasts_controller.rb
class RoastsController < ApplicationController
  before_action :set_roast, only: [:show, :edit, :update, :destroy]

  # GET /roasts
  # GET /roasts.json
  def index
    @roasts = Roast.all
  end

  # GET /roasts/1
  # GET /roasts/1.json
  def show
  end

  # GET /roasts/new
  def new
    @roast = Roast.new
  end

  # GET /roasts/1/edit
  def edit
  end

  # POST /roasts
  # POST /roasts.json
  def create
    @roast = Roast.new(roast_params)

    respond_to do |format|
      if @roast.save
        format.html { redirect_to @roast, notice: 'Roast was successfully created.' }
        format.json { render :show, status: :created, location: @roast }
      else
        format.html { render :new }
        format.json { render json: @roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roasts/1
  # PATCH/PUT /roasts/1.json
  def update
    respond_to do |format|
      if @roast.update(roast_params)
        format.html { redirect_to @roast, notice: 'Roast was successfully updated.' }
        format.json { render :show, status: :ok, location: @roast }
      else
        format.html { render :edit }
        format.json { render json: @roast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roasts/1
  # DELETE /roasts/1.json
  def destroy
    @roast.destroy
    respond_to do |format|
      format.html { redirect_to roasts_url, notice: 'Roast was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roast
      @roast = Roast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roast_params
      params.require(:roast).permit(:name, :origin, :roaster, :harvester, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_ins_helper.rb
module CheckInsHelper
end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/check_ins/_form.html.erb
<%= form_for(check_in) do |f| %>
  <% if check_in.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(check_in.errors.count, "error") %> prohibited this check_in from being saved:</h2>

      <ul>
      <% check_in.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :roast_id %>
    <%= f.collection_select(:roast_id, Roast.all, :id, :name, selected: params[:roast_id], include_blank: true) %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.select(:rating, [1,2,3,4,5]) %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_ins/edit.html.erb
<h1>Editing Check In</h1>

<%= render 'form', check_in: @check_in %>

<%= link_to 'Show', @check_in %> |
<%= link_to 'Back', check_ins_path %>

app/views/check_ins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Check Ins</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>Roast</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_ins.each do |check_in| %>
      <tr>
        <td><%= check_in.location %></td>
        <td><%= check_in.roast.name %></td>
        <td><%= check_in.created_at.strftime("%m/%d/%Y") %></td>
        <td><%= link_to 'Show', check_in %></td>
        <td><%= link_to 'Edit', edit_check_in_path(check_in) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check In', new_check_in_path %>

app/views/check_ins/new.html.erb
<h1>New Check In</h1>

<%= render 'form', check_in: @check_in %>

<%= link_to 'Back', check_ins_path %>

app/views/check_ins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @check_in.location %>
</p>

<p>
  <strong>Roast:</strong>
  <%= @check_in.roast.name %>
</p>

<p>
  <strong>Time:</strong>
  <%= @check_in.created_at %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @check_in.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @check_in.comment %>
</p>

<%= link_to 'Edit', edit_check_in_path(@check_in) %> |
<%= link_to 'Back', check_ins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffeer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrap">
    <% if user_signed_in? %>
    <nav>
      <ul>
        <li><%= link_to "My Check Ins", check_ins_path %> | </li>
        <li><%= link_to "Roasts", roasts_path %></li>
      </ul>
    </nav>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/roasts/_form.html.erb
<%= form_for(roast) do |f| %>
  <% if roast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roast.errors.count, "error") %> prohibited this roast from being saved:</h2>

      <ul>
      <% roast.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>

  <div class="field">
    <%= f.label :roaster %>
    <%= f.text_field :roaster %>
  </div>

  <div class="field">
    <%= f.label :harvester %>
    <%= f.text_field :harvester %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roasts/edit.html.erb
<h1>Editing Roast</h1>

<%= render 'form', roast: @roast %>

<%= link_to 'Show', @roast %> |
<%= link_to 'Back', roasts_path %>

app/views/roasts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roasts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Origin</th>
      <th>Roaster</th>
      <th>Harvester</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roasts.each do |roast| %>
      <tr>
        <td><%= roast.name %></td>
        <td><%= roast.origin %></td>
        <td><%= roast.roaster %></td>
        <td><%= roast.harvester %></td>
        <td><%= roast.description %></td>
        <td><%= link_to 'Show', roast %></td>
        <td><%= link_to 'Edit', edit_roast_path(roast) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roast', new_roast_path %>

app/views/roasts/new.html.erb
<h1>New Roast</h1>

<%= render 'form', roast: @roast %>

<%= link_to 'Back', roasts_path %>

app/views/roasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @roast.name %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @roast.origin %>
</p>

<p>
  <strong>Roaster:</strong>
  <%= @roast.roaster %>
</p>

<p>
  <strong>Harvester:</strong>
  <%= @roast.harvester %>
</p>

<p>
  <strong>Description:</strong>
  <%= @roast.description %>
</p>

<%= link_to 'Edit', edit_roast_path(@roast) %> |
<%= link_to 'Check In', new_check_in_path(roast_id: @roast.id) %> |
<%= link_to 'Back', roasts_path %>